# .pre-commit-config.yaml
repos:
  # Basic hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files    # blocks very large binaries in Git

  # Strip Jupyter outputs BEFORE any secret scan or lint runs
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        files: \.ipynb$

  # Linters/formatters (Python only; Ruff owns import sorting with --fix)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        types: [python]
        args: ["--fix"]        # auto-fix (incl. import order I001)
      - id: ruff-format
        types: [python]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        types: [python]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-q", "-ll", "--skip", "B101"]
        types: [python]

  # Secrets scanning (skip .ipynb; nbstripout removes outputs anyway)
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args:
          - "--baseline"
          - ".secrets.baseline"
          - "--exclude-files"
          - "\\.ipynb$"
